input_data_path: "data/heart.csv"
target_name: "target"
splitting_params:
  val_size: 0.33
  random_state: 42
train_params:
  model_type: "LogisticRegression"
dump_model: "models/model_dump.pickle"
